### ISSUE TITLE
Associate frames with video ID

### ISSUE THREAD

**Issue by jmsinusa** [vkalogeiton/yto-dataset#1]
Thank you for the dataset.
Is it possible to group the individual frames into videos? Where does one video stop, and the next one start?

**Comment by vkalogeiton** [comment]
Dear jmsinusa, 

Thank you for the interest in the YTO dataset. This release (v3) uses the same videos/shots/frames as YTO v2. You can find more details here: http://calvin.inf.ed.ac.uk/datasets/youtube-objects-dataset/. 

You can find the videos and shots for each frame in the Ranges.tar.gz: it contains a ranges.mat file for each class. Each file contains the shot partitioning for all videos as well as the video that each shot belongs to. It is a 3xS array, where S is the number of shots. 
Its structure is the following:
row 1: Index of the first frame of the shot
row 2: Index of the last frame of the shot
row 3: Index of the video the shot comes from

I hope this helps.
