### ISSUE TITLE
not able to download dataset in step 1

### ISSUE THREAD

**Issue by bragilee** [vkalogeiton/yto-dataset#2]
Hi,

Thanks for your work and sharing the dataset.

I am not able to download the dataset at all with following errors, could I get some help on what I have missed. Thanks.

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   233  100   233    0     0    272      0 --:--:-- --:--:-- --:--:--   272

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

**Comment by vkalogeiton** [comment]
Hi @bragilee 

Thank you for your interest in our dataset. 
We are now using a [new website](http://calvin-vision.net/) for our data! 
I updated the link in the repo and it should be working now. 

Please let me know if you need anything else.
